import 'dart:io';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:path_provider/path_provider.dart';
import 'package:share_plus/share_plus.dart';
import 'package:intl/intl.dart';

class ReceiptService {
  static Future<void> generateAndShareReceipt({
    required double amount,
    required String recipientId,
    required String transactionId,
    required DateTime timestamp,
    required bool isCredit,
    required String status,
  }) async {
    final pdf = pw.Document();
    
    final dateFormat = DateFormat('dd MMM yyyy, hh:mm a');
    final formattedDate = dateFormat.format(timestamp);
    final amountColor = isCredit ? PdfColors.green : PdfColors.red;
    final paymentType = isCredit ? "Payment Received" : "Payment Sent";
    final amountPrefix = isCredit ? "+" : "-";

    pdf.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a4,
        build: (pw.Context context) {
          return pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              // Header
              pw.Center(
                child: pw.Column(
                  children: [
                    pw.Text('OFFPAY', style: pw.TextStyle(fontSize: 32, fontWeight: pw.FontWeight.bold)),
                    pw.SizedBox(height: 4),
                    pw.Text('Offline Bluetooth Payments', style: pw.TextStyle(fontSize: 16, color: PdfColors.grey700)),
                  ],
                ),
              ),
              pw.SizedBox(height: 30),
              
              // Payment Type & Amount
              pw.Center(
                child: pw.Column(
                  children: [
                    pw.Text(paymentType, style: pw.TextStyle(fontSize: 20)),
                    pw.SizedBox(height: 8),
                    pw.Text(
                      '$amountPrefix ₹${amount.toStringAsFixed(2)}',
                      style: pw.TextStyle(
                        fontSize: 36,
                        fontWeight: pw.FontWeight.bold,
                        color: amountColor,
                      ),
                    ),
                  ],
                ),
              ),
              pw.SizedBox(height: 30),
              pw.Divider(thickness: 1, color: PdfColors.grey400),
              pw.SizedBox(height: 20),
              
              // Transaction Details
              pw.Text('Transaction Details', style: pw.TextStyle(fontSize: 18, fontWeight: pw.FontWeight.bold)),
              pw.SizedBox(height: 15),
              _buildDetailRow('Transaction ID', transactionId),
              _buildDetailRow('Date & Time', formattedDate),
              _buildDetailRow(isCredit ? 'Sender Device ID' : 'Recipient Device ID', recipientId),
              _buildDetailRow('Payment Status', status),
              _buildDetailRow('Payment Method', 'Offline Bluetooth BLE'),
              
              pw.Spacer(),
              pw.Divider(thickness: 1, color: PdfColors.grey400),
              pw.SizedBox(height: 10),
              
              // Footer
              pw.Center(
                child: pw.Text(
                  'This receipt was generated by OFFPAY — India\'s First Offline Payment App',
                  style: pw.TextStyle(fontSize: 12, color: PdfColors.grey600),
                  textAlign: pw.TextAlign.center,
                ),
              ),
            ],
          );
        },
      ),
    );

    // Save to temp directory
    final output = await getTemporaryDirectory();
    final file = File('${output.path}/receipt_$transactionId.pdf');
    await file.writeAsBytes(await pdf.save());

    // Share
    await Share.shareXFiles(
      [XFile(file.path)],
      text: 'OFFPAY Receipt for Transaction $transactionId',
    );
  }

  static pw.Widget _buildDetailRow(String label, String value) {
    return pw.Padding(
      padding: const pw.EdgeInsets.only(bottom: 10),
      child: pw.Row(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Expanded(
            flex: 2,
            child: pw.Text(label, style: pw.TextStyle(color: PdfColors.grey800, fontWeight: pw.FontWeight.bold)),
          ),
          pw.Expanded(
            flex: 3,
            child: pw.Text(value, style: const pw.TextStyle()),
          ),
        ],
      ),
    );
  }
}
